SiteGAD/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    #path('',RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',RedirectView.as_view(url='/accounts/login/')),
] + static(settings.STATIC_URL, document_root=(settings.STATIC_ROOT,settings.MEDIA_ROOT))

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('',views.IndexListView.as_view(),name='index'),
     path('venues/', views.venues, name='venues'),
    # path('',views.index,name='index'),
    # path('venues/', views.VenueListView.as_view(), name='venues'),
    #path('venue/<int:pk>/', views.VenueDetailView.as_view(), name='venue-detail'),
    path('venue/<int:id>/', views.venue_detail, name='venue-detail'),
    path('activityusers_list/', views.activityusers_list, name = 'activityusers-list'),
    #path('activityusers/',views.ActivityUserListView.as_view(), name ='activityusers'),
    path('venueinstances_list/', views.venueinstances_list, name='venueinstances-list'),
    #path('venueinstances/',views.VenueInstanceListView.as_view(), name = 'venueinstances'),
    path('myvenuess/', views.LoanedVenuesByUserListView.as_view(), name='my-borrowed'),
    path('add_venue/', views.add_venue, name = 'add-venue'),
    path('add_activityuser/', views.add_activityuser, name='add-activityuser'),
    path('add_venueinstance/',views.add_venueinstance, name = 'add-venueinstance'),
    path('<int:id>/', views.venueedit, name='venue-edit'),
    path('activityuser_edit/<int:id>/', views.activityuseredit, name='activityuser-edit'),
    path('venueinstance_edit/<uuid:id>/', views.venueinstanceedit, name='venueinstance-edit'),
    path('delete/<int:id>/',views.venuedelete, name = 'venue-delete'),
    path('activityuser_list/delete/<int:id>/',views.activityuserdelete, name = 'activityuser-delete'),
    path('venueinstance_list/delete/<uuid:id>/',views.venueinstancedelete, name = 'venueinstance-delete'),
    path('venueinstance_report/', views.venueinstancereport, name='venueinstance-report'),
    path('analysis/', views.analysis ,name = 'analysis'),
    
    path('imagefield/', views.image_field, name='image-field'),
    path('imageshow/',views.image_show,name='image-show'),
]

catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User
# Create your models here.
from datetime import date
from django.utils import timezone
from django.forms import ModelForm
#from datetime import datetime

##################   general model #############################
class ActivityUser(models.Model):
    identity =  models.CharField('身份別', max_length=10)
    name = models.CharField('姓名', max_length=12)
    department = models.CharField('部門', max_length=10)
    e_mail =  models.EmailField('信箱', blank=True,null=True)
    telephone = models.IntegerField('電話', blank=True,null=True)
    extension =   models.IntegerField('雲端分機', blank=True,null=True)
    
    class Meta:
        ordering = ['identity', 'name' ,'department']
        
    def get_absolute_url(self):
         """Returns the url to access a particular author instance."""
         return reverse('ActivityUser-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'


class Venue(models.Model):
   # serial_number = models.CharField(max_length=10,primary_key=True)
    site_name =  models.CharField('場地名稱', max_length=12)
    activityuser = models.ForeignKey('ActivityUser',  on_delete=models.SET_NULL, null=True, blank=True)
    area =  models.CharField('地區', max_length=10)
    club_name = models.CharField('會所名稱', max_length=12)
    site_feature =  models.CharField('場地特性', max_length=10)
    capacity =   models.IntegerField('容納人數', blank=True,null=True)
    av_device =  models.CharField('影音設備', max_length=40)
    suitable = models.CharField('適合活動', max_length=40)
    photo = models.ImageField('圖片上傳',upload_to='icons', blank=True,null=True)
    venuemanager = models.ForeignKey('VenueManager', on_delete=models.SET_NULL, null=True, blank=True )
    c_name = models.CharField(max_length=16,blank=True,null=True)
    
    def __str__(self):
        return self.site_name
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('venue-detail', args=[str(self.id)]) 

class VenueManager(models.Model):
    """Model representing a book genre."""
    name = models.CharField('姓名', max_length=200, )
    extension =   models.IntegerField('雲端分機', blank=True,null=True)
    e_mail =  models.EmailField('信箱', blank=True,null=True)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
class VenueInstance(models.Model):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole Venue')
    id = models.UUIDField('編號', primary_key=True, default=uuid.uuid4, )
    venue = models.ForeignKey('Venue', on_delete=models.SET_NULL, null=True)
    activity_name = models.TextField('活動名稱', max_length=50)
    activity_attr =  models.CharField('活動屬性', max_length=10)
    activity_category =  models.CharField('活動類別',max_length=10)
    activity_people = models.CharField('活動人數', max_length=15, null = True, blank=True, default=100)
    #activity_start = models.DateTimeField('活動開始', default=timezone.now, null = True,blank=True)
    activity_start = models.DateField('活動開始日期', null = True,blank=True)
    time_start = models.TimeField('活動開始時間',null = True,blank=True)
    activity_end = models.DateField('活動結束日期', null = True,blank=True)
    time_end = models.TimeField('活動結束時間', null = True,blank=True)
    meals_number =  models.IntegerField('用餐人數', blank=True,default=0)
    sound_control =  models.CharField('音控志工', max_length=8)
    space_use =  models.CharField('空間使用滿意度', max_length=10, help_text='請給分  1分最低5分最高')
    user_service =  models.CharField('人員服務滿意度', max_length=10, help_text='請給分  1分最低5分最高')
    report =  models.BooleanField('是否回報', default=False)
    message =  models.TextField('意見說明', max_length=100,help_text=' 請輸入你的意見 ')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
    )
    
    class Meta:
        ordering = ['activity_start','activity_end']
        permissions = (("can_mark_returned", "Set venue as returned"),)
        
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.venue.site_name},{self.venue.club_name})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

catalog/views.py
from django.shortcuts import render,redirect
from django.views import generic
from datetime import datetime
from .models import ActivityUser,Venue,VenueManager,VenueInstance
from .forms import VenueForm,VenueInstanceForm, ActivityUserForm
# Create your views here.
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import  permission_required
import uuid

import logging
logger = logging.getLogger('django')

@permission_required('catalog.can_mark_returned')
@permission_required('catalog.can_edit')
def  my_view(request):
   pass

#測試圖片上傳
def image_field(request):
    if request.method == "GET":
        return render(request, 'catalog/image_field.html', )
    elif request.method =="POST":
        sitename = request.POST.get("sitename")
        icon = request.FILES.get("icon")
        venue=Venue()
        venue.site_name = sitename
        venue.photo = icon
        venue.save()
        return HttpResponse("上傳成功")
    
#測試顯示圖片        
def image_show(request):
    sitename = request.GET.get("sitename")
    site = Venue.objects.get(site_name=sitename)
    
    #print("/static/upload"+site.photo.url)
 
    data ={
        "sitename":sitename,
        "icon_url":"/static/upload"+site.photo.url,
    }
    return render(request, 'catalog/image_show.html', context=data)
    
# class VenueDetailView(generic.DetailView):
#     model = Venue
    
def venue_detail(request,id):
    form = VenueForm()
    venuedetail = Venue.objects.get(pk=id)
    print(venuedetail)
    context = {
        #'form': form,
        'venuedetail':venuedetail,
        #加上這行會顯示圖片（不會遍歷詳細資料），但是沒有圖片的會所則無法正常顯示
        #'icon_url':"/static/upload"+venuedetail .photo.url,
    }
    return render(request, 'catalog/venue_detail.html', context=context)

class LoanedVenuesByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = VenueInstance
    template_name ='catalog/venueinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return VenueInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('activity_end')

# class MyView(LoginRequiredMixin, View):
#     login_url = '/login/'
#     redirect_field_name = 'redirect_to'


class IndexListView(generic.ListView):
    model = Venue
    paginate_by = 20
    #context_object_name = 'my_book_list'   # your own name for the list as a template variable
    #queryset = Book.objects.filter(title__icontains='Game')[:4] # Get 5 books containing the title war
    template_name = 'index.html'  # Specify your own template name/location

def venues(request):
    """View function for home page of site."""
    #get currnet year
    now = datetime.now()
    current_year = now.year
    # Generate counts of some of the main objects
    num_venues = Venue.objects.all().count()
    num_instances = VenueInstance.objects.all().count()
    users_list = ActivityUser.objects.all()
    venues = Venue.objects.all().order_by('-id')
    # Available books (status = 'a')
    num_instances_available = VenueInstance.objects.filter(status__exact='a').count()
    # The 'all()' is implied by default.
    num_activityusers = ActivityUser.objects.count()
    #Number of visits to this view , as counted in the session variable.
    num_visists = request.session.get('num_visits' ,0)
    request.session['num_visits'] = num_visists + 1
    
    context = {
        'num_venues': num_venues,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_activityusers': num_activityusers,
        'num_visits' : num_visists,
        'venues':venues,
        'current_year':current_year,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/venue_list.html', context=context)

def analysis(request):
    return HttpResponse("統計分析")
   
##################################################    
# class ActivityUserListView(generic.ListView):
#     model = ActivityUser
#     template_name = 'activityusers/activityuser_list.html' 
 
def activityusers_list(request):
    activityusers = ActivityUser.objects.all().order_by('-id')
    return render(request, 'catalog/activityusers_list.html', {'activityusers':activityusers})

     
# class VenueInstanceListView(generic.ListView):
#     model = VenueInstance
#     venueinstances = VenueInstance.objects.all().order_by('activity_start')
#     template_name = 'VenueInstances/venueinstance_list.html' 
    
def venueinstances_list(request):
    venueinstances = VenueInstance.objects.all()
    context = {
        'venueinstances':venueinstances
    }
    return render(request, 'catalog/venueinstances_list.html', context=context)

########################ADD######################   
# VenueForm setting
def add_venue(request):
    submitted = False
    if request.method == "POST" :
        form = VenueForm(request.POST)
        if form .is_valid():
            form.save()
            return HttpResponseRedirect('/catalog/add_venue?submitted=True')
    else:
            form = VenueForm
            if 'submitted' in request.GET:
                submitted = True
            return render(request, 'catalog/add_venue.html', {'form':form, 'submitted':submitted})

def add_activityuser(request):
    submitted = False
    if request.method == "POST" :
        form = ActivityUserForm(request.POST)
        if form .is_valid():
            form.save()
            return HttpResponseRedirect('/catalog/add_activityuser?submitted=True')
    else:
            form = ActivityUserForm
            if 'submitted' in request.GET:
                submitted = True
            return render(request, 'catalog/add_activityuser.html', {'form':form, 'submitted':submitted})

#venueinstanceform  setting 
# 日期輸入格式不正確，網頁會顯示錯誤
def  add_venueinstance(request):
    submitted = False
    if request.method == "POST" :
        form = VenueInstanceForm(request.POST)
        if form .is_valid():
            form.save()
            return HttpResponseRedirect('/catalog/add_venueinstance?submitted=True')
    else:
            form = VenueInstanceForm
            if 'submitted' in request.GET:
                submitted = True
            return render(request, 'catalog/add_venueinstance.html', {'form':form, 'submitted':submitted})



####################EDIT#########################
def venueedit(request, id=0):
    if request.method == "GET":
        if id ==0:
            form = VenueForm()
        else:
            venue = Venue.objects.get(pk = id)
            form =  VenueForm(instance = venue)
        return render(request, "catalog/venue_update.html", {'form':form})
    else:
        if id ==0:
            form = VenueForm(request.POST)
        else:
            venue = Venue.objects.get(pk = id)
            form = VenueForm(request.POST, instance = venue)
        if form.is_valid():
            form.save()
        return redirect('venues')

def activityuseredit(request, id=0):
    if request.method == "GET":
        if id ==0:
            form = ActivityUserForm()
        else:
            activityuser = ActivityUser.objects.get(pk = id)
            form =  ActivityUserForm(instance = activityuser)
        return render(request, "catalog/activityuser_update.html", {'form':form})
    else:
        if id ==0:
            form = ActivityUserForm(request.POST)
        else:
            activityuser = ActivityUser.objects.get(pk = id)
            form =  ActivityUserForm(request.POST, instance = activityuser)
        if form.is_valid():
            form.save()
        return redirect('activityusers-list')

def venueinstanceedit(request, id=0):
    if request.method == "GET":
        if id ==0:
            form = VenueInstanceForm()
        else:
            venueinstance = VenueInstance.objects.get(pk = id)
            form =  VenueInstanceForm(instance = venueinstance)
        return render(request, "catalog/venueinstance_update.html", {'form':form})
    else:
        if id ==0:
            form = VenueInstanceForm(request.POST)
        else:
            venueinstance = VenueInstance.objects.get(pk = id)
            form = VenueInstanceForm(request.POST, instance = venueinstance)
        if form.is_valid():
            form.save()
        return redirect('venueinstances-list')

##########report####################
def venueinstancereport(request):
    return HttpResponse("回報成功")


##############Delete################
def venuedelete(request, id):
    venue = Venue.objects.get(pk = id)
    venue.delete()
    return redirect('venues')

def activityuserdelete(request, id):
    activityuser = ActivityUser.objects.get(pk = id)
    activityuser.delete()
    return redirect('activityusers-list')

def venueinstancedelete(request, id):
    venueinstance = VenueInstance.objects.get(pk = id)
    venueinstance.delete()
    return redirect('venueinstances-list')



 

catalog/templates/catalog/activityuser_update.html
{% extends "base_generic.html" %}

{% block content %}
<h3> 活動編輯</h3>
<br/>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="form-group col-md-6">
                {{ form.as_p }}
                <div class = "row">
                    <div class="col-md-8">
                        <input type = "submit" value ="更新" class = "btn btn-success">
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'activityusers-list' %}" class = "btn btn-secondary btn-block btn-log">
                        <i class = "fas fa-stream"></i> 回上一頁</a>
                <div>
            </div>
        </div>
    </form>
{% endblock  %}

catalog/templates/catalog/activityusers_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1> 申請人管理 </h1>
<div>
<h2 align="left">申請人所有資料&nbsp;&nbsp;
<a href="{% url 'add-activityuser' %}" class="btn btn-success">新增</a>&nbsp;&nbsp;</h2>
<!--<a href="add_venueinstance" class="btn btn-success">新增2</a>&nbsp;&nbsp;</h2>-->
<form action="." method="POST" name="form2">

{% csrf_token %}

<table class="table table-bordered table-striped">
<thead class="thead-dark">
  <tr>
	  <th>編號</th><th>身份別</th><th>姓名</th><th>部門</th>
	  <th>信箱</th><th>電話</th><th>雲端分機</th><th>管理</th>
  </tr>
</thead>
<tbody>
	{% for actusers in activityusers %}
		<tr>
			<td>{{ actusers.id }} </td>
			<td>{{  actusers.identity }} </td>
			<td>{{ actusers.name}} </td>
			<td>{{ actusers.department }} </td>
			<td>{{ actusers.e_mail }} </td>
			<td>{{ actusers.telephone}} </td>
			<td>{{ actusers.extension }} </td>
            <td><!--need to modify-->
                <a href="{% url 'activityuser-edit' actusers.id %}" title="編輯" class="btn btn-info">編輯</a>	
                <a href="{% url 'activityuser-delete' actusers.id %}" title="刪除" class="btn btn-danger">刪除</a>
            </td>
		</tr>
	{% endfor %}
</tbody>
</table>
</div>

  <!--<p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>-->
{% endblock %}

catalog/templates/catalog/add_activityuser.html
{% extends "base_generic.html" %}

{% block content %}
        
        <h3> 申請人申請單</h3>
        <br/>
        {% if submitted %}
                    申請人申請成功 !!!
        {% else %}
            <form action = "" method = POST>
                {% csrf_token %}
                <div class="form-group">
                <div class="form-group col-md-6">
                {{ form.as_p }}
                 <div class = "row">
                    <div class="col-md-8">
                        <input type = "submit" value = "送出" class = "btn btn-success">
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'activityusers-list' %}" class = "btn btn-secondary btn-block btn-log">
                                <i class = "fas fa-stream"></i> 回上一頁
                        </a>
                    </div>
                </div>
                </div>
            </form>
        {% endif %}
        
{% endblock %}

catalog/templates/catalog/add_venue.html
{% extends "base_generic.html" %}

{% block content %}
        
        <h3> 場地申請單</h3>
        <br/>
        {% if submitted %}
                    場地申請成功 !!!
        {% else %}
            <form action = "" method = POST>
                {% csrf_token %}
                <div class="form-group">
                <div class="form-group col-md-6">
                {{ form.as_p }}
                 <div class = "row">
                    <div class="col-md-8">
                        <input type = "submit" value = "送出" class = "btn btn-success">
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'venues' %}" class = "btn btn-secondary btn-block btn-log">
                                <i class = "fas fa-stream"></i> 回上一頁
                        </a>
                    </div>
                </div>
                </div>
            </form>
        {% endif %}
        
{% endblock %}

catalog/templates/catalog/add_venueinstance.html
{% extends "base_generic.html" %}

{% block content %}
        
        <h3> 活動申請單</h3>
        <br/>
        {% if submitted %}
                    活動申請成功 !!!
        {% else %}
            <form action = "" method = POST>
                {% csrf_token %}
                <div class="form-group">
                <div class="form-group col-md-6">
                {{ form.as_p }}
                 <div class = "row">
                    <div class="col-md-8">
                        <input type = "submit" value = "送出" class = "btn btn-success">
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'venueinstances-list' %}" class = "btn btn-secondary btn-block btn-log">
                                <i class = "fas fa-stream"></i> 回上一頁
                        </a>
                    </div>
                </div>
                </div>
            </form>
        {% endif %}
        
{% endblock %}

 {% comment  %}

{% block js %}
 
<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
  <script>
$(function () {
      $("#id_activity_start").datetimepicker( {
         format:'Y-m-d H:i',
      });
    });
  </script>
{% endblock %}

{% endcomment %}

catalog/templates/catalog/detail1.html
h1>{{ venue.site_name }}</h1>
<ul>
{% for choice in activityuser.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

catalog/templates/catalog/image_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>showimage</title>
</head>
<body>
{{ sitename}}
<img src="{{icon_url}}" alt="{{sitename}}">    
</body>
</html>

catalog/templates/catalog/venue_delete.html
{{venue}}

catalog/templates/catalog/venue_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>場地名稱: {{ venuedetail.site_name }}</h1>


  <!--<p><strong>Author:</strong> <a href="">{{ venue.area }}</a></p> -->
  <!-- author detail link not yet defined -->
  <p><strong>地區:</strong> {{ venuedetail.area }}</p>
  <p><strong>會所名稱:</strong> {{ venuedetail.club_name }}</p>
  <p><strong>場地特性:</strong> {{ venuedetail.site_feature }}</p>
  <p><strong>容納人數:</strong> {{ venuedetail.capacity }}</p>
  <p><strong>影音設備:</strong> {{ venuedetail.av_device }}</p>
  <p><strong>適合活動:</strong> {{ venuedetail.suitable }}</p>

<div class="row">
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <p><strong>場地照片:</strong></p>
            <img class="card-img-top" src="{{icon_url}}">
          </div>
      </div>
</div>

    {% comment %}
    <div>
  <p><strong>場地照片:</strong><img src="{{venue.photo.url}}" />
  {{ venue.photo }}
  </p>
  </div>



  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
  {% endcomment %}
{% endblock %}

catalog/templates/catalog/venue_list.html
{% extends "base_generic.html" %}

{% block content %}
 
<!-- ########forms######## -->
<div>
<h2 align="left">顯示資料表所有資料&nbsp;&nbsp;
<a href="{% url 'add-venue' %}" class="btn btn-success">新增</a>&nbsp;&nbsp;</h2>
<!--<a href="add_venueinstance" class="btn btn-success">新增2</a>&nbsp;&nbsp;</h2>-->
<form action="." method="POST" name="form1">

{% csrf_token %}
<!--<table border="1" cellpadding="0" cellspacing="0">-->
<table class="table table-bordered table-striped">
<thead class="thead-dark">
  <tr>
	  <!--<th>編號</th>--><th>場地名稱</th><!--<th>活動申請人</th>--><th>地區</th>
	  <th>會所名稱</th><th>場地特性</th><th>容納人數</th><th>影音設備</th>
    <th>適合活動</th><th>場地管理人</th><th>分機.</th><th>管理</th>
  </tr>
</thead>
<tbody>
	{% for venue in venues %}
		<tr>
			<!--<td>{{ venue.id }} </td>-->
			<td>{{ venue.site_name }} </td>
			<!--<td>{{ venue.activityuser}} </td>-->
			<td>{{ venue.area }} </td>
			<td>{{ venue.club_name }} </td>
			<td>{{ venue.site_feature}} </td>
			<td>{{ venue.capacity }} </td>
      		<td>{{ venue.av_device }} </td>
      		<td>{{ venue.suitable }} </td>
      		<td>{{ venue.venuemanager }} </td>
      		<td>{{ venue.venuemanager.extension }} </td>
            <td>
                <a href="{% url 'venue-edit' venue.id %}" title="編輯" class="btn btn-info">編輯</a>	
                <a href="{% url 'venue-delete' venue.id %}" title="刪除" class="btn btn-danger">刪除</a>
            </td>
		</tr>
	{% endfor %}
</tbody>
</table>
</form>
</div>
  {% endblock %}
  

catalog/templates/catalog/venue_update.html
{% extends "base_generic.html" %}

{% block content %}
<h3> 場地編輯</h3>
<br/>
    <form action="" method="POST" >
        {% csrf_token %}
        <div class="form-group">
            <div class="form-group col-md-6">
                {{ form.as_p }}
                <div class = "row">
                    <div class="col-md-8">
                        <input type = "submit" value ="更新" class = "btn btn-success">
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'venues' %}" class = "btn btn-secondary btn-block btn-log">
                        <i class = "fas fa-stream"></i> 回上一頁</a>
                <div>
            </div>
        </div>
    </form>
{% endblock  %}

catalog/templates/catalog/venueinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed venues</h1>

    {% if venueinstance_list %}
    <ul>

      {% for venueinst in venueinstance_list %}
      <li class="{% if venueinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'venue-detail' venueinst.venue.pk %}">{{venueinst.venue.site_name}}</a> ({{ venueinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}